# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/program/edward/python/edo_ThreePointMatherUI/edo_ThreePointMatherUIDesign.ui'
#
# Created: Wed Aug 13 13:48:18 2014
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from headfile import *

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_edo_ThreePointMatherUI(object):
    def setupUi(self, edo_ThreePointMatherUI):
        edo_ThreePointMatherUI.setObjectName(_fromUtf8("edo_ThreePointMatherUI"))
        edo_ThreePointMatherUI.resize(258, 486)
        self.centralwidget = QtGui.QWidget(edo_ThreePointMatherUI)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 121, 31))
        self.label.setStyleSheet(_fromUtf8("font: 75 8pt \"Ravie\";"))
        self.label.setObjectName(_fromUtf8("label"))
        self.sourceOp_le = QtGui.QLineEdit(self.centralwidget)
        self.sourceOp_le.setGeometry(QtCore.QRect(80, 50, 51, 20))
        self.sourceOp_le.setObjectName(_fromUtf8("sourceOp_le"))
        self.sourceXp_le = QtGui.QLineEdit(self.centralwidget)
        self.sourceXp_le.setGeometry(QtCore.QRect(140, 50, 51, 20))
        self.sourceXp_le.setObjectName(_fromUtf8("sourceXp_le"))
        self.sourceZp_le = QtGui.QLineEdit(self.centralwidget)
        self.sourceZp_le.setGeometry(QtCore.QRect(200, 50, 51, 20))
        self.sourceZp_le.setObjectName(_fromUtf8("sourceZp_le"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 121, 31))
        self.label_2.setStyleSheet(_fromUtf8("font: 75 8pt \"Ravie\";"))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.shear_cb = QtGui.QCheckBox(self.centralwidget)
        self.shear_cb.setGeometry(QtCore.QRect(10, 160, 181, 18))
        self.shear_cb.setStyleSheet(_fromUtf8("font: 75 8pt \"Ravie\";"))
        self.shear_cb.setChecked(False)
        self.shear_cb.setObjectName(_fromUtf8("shear_cb"))
        self.transformMatch_bt = QtGui.QPushButton(self.centralwidget)
        self.transformMatch_bt.setGeometry(QtCore.QRect(10, 220, 237, 56))
        self.transformMatch_bt.setStyleSheet(_fromUtf8("background:url(:/icon/TransformMatch_OneToMulti.jpg)"))
        self.transformMatch_bt.setText(_fromUtf8(""))
        self.transformMatch_bt.setObjectName(_fromUtf8("transformMatch_bt"))
        self.targetZp_le = QtGui.QLineEdit(self.centralwidget)
        self.targetZp_le.setGeometry(QtCore.QRect(200, 120, 51, 20))
        self.targetZp_le.setObjectName(_fromUtf8("targetZp_le"))
        self.targetOp_le = QtGui.QLineEdit(self.centralwidget)
        self.targetOp_le.setGeometry(QtCore.QRect(80, 120, 51, 20))
        self.targetOp_le.setObjectName(_fromUtf8("targetOp_le"))
        self.targetXp_le = QtGui.QLineEdit(self.centralwidget)
        self.targetXp_le.setGeometry(QtCore.QRect(140, 120, 51, 20))
        self.targetXp_le.setObjectName(_fromUtf8("targetXp_le"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(80, 20, 21, 31))
        self.label_3.setStyleSheet(_fromUtf8("font: 75 8pt \"Ravie\";"))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(140, 20, 21, 31))
        self.label_4.setStyleSheet(_fromUtf8("font: 75 8pt \"Ravie\";"))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(200, 20, 21, 31))
        self.label_5.setStyleSheet(_fromUtf8("font: 75 8pt \"Ravie\";"))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(80, 90, 21, 31))
        self.label_6.setStyleSheet(_fromUtf8("font: 75 8pt \"Ravie\";"))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(140, 90, 21, 31))
        self.label_7.setStyleSheet(_fromUtf8("font: 75 8pt \"Ravie\";"))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(200, 90, 21, 31))
        self.label_8.setStyleSheet(_fromUtf8("font: 75 8pt \"Ravie\";"))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.loadSource_bt = QtGui.QPushButton(self.centralwidget)
        self.loadSource_bt.setGeometry(QtCore.QRect(10, 50, 61, 21))
        self.loadSource_bt.setStyleSheet(_fromUtf8("font: 75 8pt \"Ravie\";"))
        self.loadSource_bt.setObjectName(_fromUtf8("loadSource_bt"))
        self.loadTarget_bt = QtGui.QPushButton(self.centralwidget)
        self.loadTarget_bt.setGeometry(QtCore.QRect(10, 120, 61, 21))
        self.loadTarget_bt.setStyleSheet(_fromUtf8("font: 75 8pt \"Ravie\";"))
        self.loadTarget_bt.setObjectName(_fromUtf8("loadTarget_bt"))
        self.transformMatchMO_bt = QtGui.QPushButton(self.centralwidget)
        self.transformMatchMO_bt.setGeometry(QtCore.QRect(10, 290, 237, 56))
        self.transformMatchMO_bt.setStyleSheet(_fromUtf8("background:url(:/icon/TransformMatch_MultiToOne.jpg)"))
        self.transformMatchMO_bt.setText(_fromUtf8(""))
        self.transformMatchMO_bt.setObjectName(_fromUtf8("transformMatchMO_bt"))
        self.controlerMatch_bt = QtGui.QPushButton(self.centralwidget)
        self.controlerMatch_bt.setGeometry(QtCore.QRect(10, 400, 237, 56))
        self.controlerMatch_bt.setStyleSheet(_fromUtf8("background:url(:/icon/AttachCtrl.jpg)"))
        self.controlerMatch_bt.setText(_fromUtf8(""))
        self.controlerMatch_bt.setObjectName(_fromUtf8("controlerMatch_bt"))
        self.undoflush_cb = QtGui.QCheckBox(self.centralwidget)
        self.undoflush_cb.setGeometry(QtCore.QRect(10, 190, 181, 18))
        self.undoflush_cb.setStyleSheet(_fromUtf8("font: 75 8pt \"Ravie\";"))
        self.undoflush_cb.setChecked(False)
        self.undoflush_cb.setObjectName(_fromUtf8("undoflush_cb"))
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(20, 360, 151, 31))
        self.label_9.setStyleSheet(_fromUtf8("font: 75 8pt \"Ravie\";"))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.constraint_pb = QtGui.QSpinBox(self.centralwidget)
        self.constraint_pb.setGeometry(QtCore.QRect(170, 360, 71, 31))
        self.constraint_pb.setMaximum(20)
        self.constraint_pb.setObjectName(_fromUtf8("constraint_pb"))
        edo_ThreePointMatherUI.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(edo_ThreePointMatherUI)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 258, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        edo_ThreePointMatherUI.setMenuBar(self.menubar)
        self.actionHow_to_use = QtGui.QAction(edo_ThreePointMatherUI)
        self.actionHow_to_use.setObjectName(_fromUtf8("actionHow_to_use"))
        self.actionAbout_me = QtGui.QAction(edo_ThreePointMatherUI)
        self.actionAbout_me.setObjectName(_fromUtf8("actionAbout_me"))
        self.menuHelp.addAction(self.actionHow_to_use)
        self.menuHelp.addAction(self.actionAbout_me)
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(edo_ThreePointMatherUI)
        QtCore.QMetaObject.connectSlotsByName(edo_ThreePointMatherUI)

    def retranslateUi(self, edo_ThreePointMatherUI):
        edo_ThreePointMatherUI.setWindowTitle(_translate("edo_ThreePointMatherUI", "edo_ThreePointMatherUI", None))
        self.label.setText(_translate("edo_ThreePointMatherUI", "Source Triangle:", None))
        self.sourceOp_le.setText(_translate("edo_ThreePointMatherUI", "0", None))
        self.sourceXp_le.setText(_translate("edo_ThreePointMatherUI", "1", None))
        self.sourceZp_le.setText(_translate("edo_ThreePointMatherUI", "2", None))
        self.label_2.setText(_translate("edo_ThreePointMatherUI", "Target Triangle:", None))
        self.shear_cb.setText(_translate("edo_ThreePointMatherUI", "obsolute ( use shear )", None))
        self.targetZp_le.setText(_translate("edo_ThreePointMatherUI", "2", None))
        self.targetOp_le.setText(_translate("edo_ThreePointMatherUI", "0", None))
        self.targetXp_le.setText(_translate("edo_ThreePointMatherUI", "1", None))
        self.label_3.setText(_translate("edo_ThreePointMatherUI", "O:", None))
        self.label_4.setText(_translate("edo_ThreePointMatherUI", "X:", None))
        self.label_5.setText(_translate("edo_ThreePointMatherUI", "Z:", None))
        self.label_6.setText(_translate("edo_ThreePointMatherUI", "O:", None))
        self.label_7.setText(_translate("edo_ThreePointMatherUI", "X:", None))
        self.label_8.setText(_translate("edo_ThreePointMatherUI", "Z:", None))
        self.loadSource_bt.setText(_translate("edo_ThreePointMatherUI", "LOAD", None))
        self.loadTarget_bt.setText(_translate("edo_ThreePointMatherUI", "LOAD", None))
        self.undoflush_cb.setText(_translate("edo_ThreePointMatherUI", "undo flush", None))
        self.label_9.setText(_translate("edo_ThreePointMatherUI", "Constraint Parent:", None))
        self.menuHelp.setTitle(_translate("edo_ThreePointMatherUI", "help", None))
        self.actionHow_to_use.setText(_translate("edo_ThreePointMatherUI", "how to use", None))
        self.actionAbout_me.setText(_translate("edo_ThreePointMatherUI", "about me", None))

import edo_ThreePointMatherUI_rc
