# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\work\src\validation\resources\Check_form.ui'
#
# Created: Sat Jan 07 17:08:47 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

#from PySide import QtCore, QtGui
from head import *

class Ui_Check_form(object):
    def setupUi(self, Check_form):
        Check_form.setObjectName("Check_form")
        Check_form.resize(552, 477)
        self.verticalLayout = QtGui.QVBoxLayout(Check_form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.logo_label = QtGui.QLabel(Check_form)
        self.logo_label.setMinimumSize(QtCore.QSize(50, 50))
        self.logo_label.setMaximumSize(QtCore.QSize(50, 50))
        self.logo_label.setText("")
        self.logo_label.setPixmap(QtGui.QPixmap("./icons/validation.png"))
        self.logo_label.setScaledContents(True)
        self.logo_label.setObjectName("logo_label")
        self.horizontalLayout_4.addWidget(self.logo_label)
        self.label_2 = QtGui.QLabel(Check_form)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.line = QtGui.QFrame(Check_form)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.item_area_group = QtGui.QGroupBox(Check_form)
        self.item_area_group.setMinimumSize(QtCore.QSize(150, 0))
        self.item_area_group.setMaximumSize(QtCore.QSize(300, 16777215))
        self.item_area_group.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.item_area_group.setObjectName("item_area_group")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.item_area_group)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setContentsMargins(9, 5, 9, 5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.item_area_layout = QtGui.QVBoxLayout()
        self.item_area_layout.setSpacing(0)
        self.item_area_layout.setObjectName("item_area_layout")
        self.verticalLayout_2.addLayout(self.item_area_layout)
        spacerItem1 = QtGui.QSpacerItem(20, 439, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.refresh_btn = QtGui.QToolButton(self.item_area_group)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icons/refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.refresh_btn.setIcon(icon)
        self.refresh_btn.setAutoRaise(True)
        self.refresh_btn.setObjectName("refresh_btn")
        self.horizontalLayout_3.addWidget(self.refresh_btn)
        self.run_btn = QtGui.QToolButton(self.item_area_group)
        self.run_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("/icons/play_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.run_btn.setIcon(icon1)
        self.run_btn.setAutoRaise(True)
        self.run_btn.setObjectName("run_btn")
        self.horizontalLayout_3.addWidget(self.run_btn)
        self.continue_btn = QtGui.QToolButton(self.item_area_group)
        self.continue_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../icons/gono.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.continue_btn.setIcon(icon2)
        self.continue_btn.setAutoRaise(True)
        self.continue_btn.setObjectName("continue_btn")
        self.horizontalLayout_3.addWidget(self.continue_btn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2.addWidget(self.item_area_group)
        self.info_area_group = QtGui.QGroupBox(Check_form)
        self.info_area_group.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.info_area_group.setObjectName("info_area_group")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.info_area_group)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setContentsMargins(0, 5, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea = QtGui.QScrollArea(self.info_area_group)
        self.scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea.setLineWidth(0)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 374, 340))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setSpacing(5)
        self.verticalLayout_4.setContentsMargins(9, 0, 9, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.info_area_layout = QtGui.QVBoxLayout()
        self.info_area_layout.setObjectName("info_area_layout")
        self.verticalLayout_4.addLayout(self.info_area_layout)
        spacerItem3 = QtGui.QSpacerItem(20, 484, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.horizontalLayout_2.addWidget(self.info_area_group)
        self.horizontalLayout_2.setStretch(1, 10)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.logging_label = QtGui.QLabel(Check_form)
        self.logging_label.setText("")
        self.logging_label.setObjectName("logging_label")
        self.horizontalLayout.addWidget(self.logging_label)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.cancle_btn = QtGui.QPushButton(Check_form)
        self.cancle_btn.setMinimumSize(QtCore.QSize(75, 0))
        self.cancle_btn.setObjectName("cancle_btn")
        self.horizontalLayout.addWidget(self.cancle_btn)
        self.skip_btn = QtGui.QPushButton(Check_form)
        self.skip_btn.setMinimumSize(QtCore.QSize(75, 0))
        self.skip_btn.setObjectName("skip_btn")
        self.horizontalLayout.addWidget(self.skip_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Check_form)
        QtCore.QObject.connect(self.cancle_btn, QtCore.SIGNAL("clicked()"), Check_form.close)
        QtCore.QMetaObject.connectSlotsByName(Check_form)

    def retranslateUi(self, Check_form):
        Check_form.setWindowTitle(QtGui.QApplication.translate("Check_form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Check_form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">  Check for current scene</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.item_area_group.setTitle(QtGui.QApplication.translate("Check_form", "检查项", None, QtGui.QApplication.UnicodeUTF8))
        self.refresh_btn.setText(QtGui.QApplication.translate("Check_form", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.info_area_group.setTitle(QtGui.QApplication.translate("Check_form", "信息", None, QtGui.QApplication.UnicodeUTF8))
        self.cancle_btn.setText(QtGui.QApplication.translate("Check_form", "Cancle", None, QtGui.QApplication.UnicodeUTF8))
        self.skip_btn.setText(QtGui.QApplication.translate("Check_form", "Skip", None, QtGui.QApplication.UnicodeUTF8))

