# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/program/edward/python/edo_skeletonDrivingBallToolUI/edo_skeletonDrivingBallToolUIDesign.ui'
#
# Created: Thu Oct 30 18:12:21 2014
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from headfile import *

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_edo_skeletonDrivingBallToolUI(object):
    def setupUi(self, edo_skeletonDrivingBallToolUI):
        edo_skeletonDrivingBallToolUI.setObjectName(_fromUtf8("edo_skeletonDrivingBallToolUI"))
        edo_skeletonDrivingBallToolUI.resize(344, 583)
        self.centralwidget = QtGui.QWidget(edo_skeletonDrivingBallToolUI)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 331, 531))
        self.tabWidget.setStyleSheet(_fromUtf8("font: 14pt \"华文琥珀\";"))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.create = QtGui.QWidget()
        self.create.setObjectName(_fromUtf8("create"))
        self.connectcbs_bt = QtGui.QPushButton(self.create)
        self.connectcbs_bt.setGeometry(QtCore.QRect(10, 110, 291, 51))
        self.connectcbs_bt.setStyleSheet(_fromUtf8("font: 14pt \"华文琥珀\";"))
        self.connectcbs_bt.setObjectName(_fromUtf8("connectcbs_bt"))
        self.edirmodel_cb = QtGui.QCheckBox(self.create)
        self.edirmodel_cb.setGeometry(QtCore.QRect(10, 10, 301, 31))
        self.edirmodel_cb.setStyleSheet(_fromUtf8("font: 14pt \"华文琥珀\";"))
        self.edirmodel_cb.setChecked(True)
        self.edirmodel_cb.setObjectName(_fromUtf8("edirmodel_cb"))
        self.createskdb_bt = QtGui.QPushButton(self.create)
        self.createskdb_bt.setGeometry(QtCore.QRect(10, 50, 291, 51))
        self.createskdb_bt.setStyleSheet(_fromUtf8("font: 14pt \"华文琥珀\";"))
        self.createskdb_bt.setObjectName(_fromUtf8("createskdb_bt"))
        self.loadskdb_bt = QtGui.QPushButton(self.create)
        self.loadskdb_bt.setGeometry(QtCore.QRect(10, 230, 101, 31))
        self.loadskdb_bt.setStyleSheet(_fromUtf8("font: 14pt \"华文琥珀\";"))
        self.loadskdb_bt.setObjectName(_fromUtf8("loadskdb_bt"))
        self.loadskdb_le = QtGui.QLineEdit(self.create)
        self.loadskdb_le.setGeometry(QtCore.QRect(120, 230, 181, 31))
        self.loadskdb_le.setStyleSheet(_fromUtf8("font: 14pt \"Adobe Arabic\";"))
        self.loadskdb_le.setObjectName(_fromUtf8("loadskdb_le"))
        self.attribute_lw = QtGui.QListWidget(self.create)
        self.attribute_lw.setGeometry(QtCore.QRect(10, 310, 81, 171))
        self.attribute_lw.setStyleSheet(_fromUtf8("font: 14pt \"Adobe Arabic\";"))
        self.attribute_lw.setObjectName(_fromUtf8("attribute_lw"))
        self.rotation_lw = QtGui.QListWidget(self.create)
        self.rotation_lw.setGeometry(QtCore.QRect(110, 310, 201, 171))
        self.rotation_lw.setStyleSheet(_fromUtf8("font: 14pt \"Adobe Arabic\";"))
        self.rotation_lw.setObjectName(_fromUtf8("rotation_lw"))
        self.label_3 = QtGui.QLabel(self.create)
        self.label_3.setGeometry(QtCore.QRect(10, 280, 81, 16))
        self.label_3.setStyleSheet(_fromUtf8("font: 14pt \"华文琥珀\";"))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.create)
        self.label_4.setGeometry(QtCore.QRect(110, 280, 81, 16))
        self.label_4.setStyleSheet(_fromUtf8("font: 14pt \"华文琥珀\";"))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.loadctrl_bt = QtGui.QPushButton(self.create)
        self.loadctrl_bt.setGeometry(QtCore.QRect(10, 190, 101, 31))
        self.loadctrl_bt.setStyleSheet(_fromUtf8("font: 14pt \"华文琥珀\";"))
        self.loadctrl_bt.setObjectName(_fromUtf8("loadctrl_bt"))
        self.loadctrl_le = QtGui.QLineEdit(self.create)
        self.loadctrl_le.setGeometry(QtCore.QRect(120, 190, 181, 31))
        self.loadctrl_le.setStyleSheet(_fromUtf8("font: 14pt \"Adobe Arabic\";"))
        self.loadctrl_le.setText(_fromUtf8(""))
        self.loadctrl_le.setObjectName(_fromUtf8("loadctrl_le"))
        self.tabWidget.addTab(self.create, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.createskdbforlcbr_bt = QtGui.QPushButton(self.tab)
        self.createskdbforlcbr_bt.setGeometry(QtCore.QRect(10, 40, 291, 61))
        self.createskdbforlcbr_bt.setStyleSheet(_fromUtf8("font: 14pt \"华文琥珀\";"))
        self.createskdbforlcbr_bt.setObjectName(_fromUtf8("createskdbforlcbr_bt"))
        self.nofinger_cb = QtGui.QCheckBox(self.tab)
        self.nofinger_cb.setGeometry(QtCore.QRect(10, 10, 301, 31))
        self.nofinger_cb.setStyleSheet(_fromUtf8("font: 14pt \"华文琥珀\";"))
        self.nofinger_cb.setChecked(True)
        self.nofinger_cb.setObjectName(_fromUtf8("nofinger_cb"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.mirror = QtGui.QWidget()
        self.mirror.setObjectName(_fromUtf8("mirror"))
        self.groupBox = QtGui.QGroupBox(self.mirror)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 291, 451))
        self.groupBox.setStyleSheet(_fromUtf8("font: 14pt \"华文琥珀\";"))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.mirrorskdb_bt = QtGui.QPushButton(self.groupBox)
        self.mirrorskdb_bt.setEnabled(False)
        self.mirrorskdb_bt.setGeometry(QtCore.QRect(10, 390, 271, 51))
        self.mirrorskdb_bt.setStyleSheet(_fromUtf8("font: 14pt \"华文琥珀\";"))
        self.mirrorskdb_bt.setObjectName(_fromUtf8("mirrorskdb_bt"))
        self.mirrordbs_bt = QtGui.QPushButton(self.groupBox)
        self.mirrordbs_bt.setGeometry(QtCore.QRect(10, 100, 271, 51))
        self.mirrordbs_bt.setStyleSheet(_fromUtf8("font: 14pt \"华文琥珀\";"))
        self.mirrordbs_bt.setObjectName(_fromUtf8("mirrordbs_bt"))
        self.from_le = QtGui.QLineEdit(self.groupBox)
        self.from_le.setGeometry(QtCore.QRect(10, 50, 101, 41))
        self.from_le.setStyleSheet(_fromUtf8("font: 14pt \"华文琥珀\";"))
        self.from_le.setObjectName(_fromUtf8("from_le"))
        self.to_le = QtGui.QLineEdit(self.groupBox)
        self.to_le.setGeometry(QtCore.QRect(180, 50, 101, 41))
        self.to_le.setStyleSheet(_fromUtf8("font: 14pt \"华文琥珀\";"))
        self.to_le.setObjectName(_fromUtf8("to_le"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 30, 54, 12))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(180, 30, 54, 12))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.switch_bt = QtGui.QPushButton(self.groupBox)
        self.switch_bt.setGeometry(QtCore.QRect(120, 50, 51, 41))
        self.switch_bt.setStyleSheet(_fromUtf8("font: 14pt \"华文琥珀\";"))
        self.switch_bt.setObjectName(_fromUtf8("switch_bt"))
        self.mirrorsdk_bt = QtGui.QPushButton(self.groupBox)
        self.mirrorsdk_bt.setEnabled(False)
        self.mirrorsdk_bt.setGeometry(QtCore.QRect(10, 340, 271, 51))
        self.mirrorsdk_bt.setStyleSheet(_fromUtf8("font: 14pt \"华文琥珀\";"))
        self.mirrorsdk_bt.setObjectName(_fromUtf8("mirrorsdk_bt"))
        self.connectBsToBs_bt = QtGui.QPushButton(self.groupBox)
        self.connectBsToBs_bt.setGeometry(QtCore.QRect(10, 160, 271, 51))
        self.connectBsToBs_bt.setStyleSheet(_fromUtf8("font: 14pt \"华文琥珀\";"))
        self.connectBsToBs_bt.setObjectName(_fromUtf8("connectBsToBs_bt"))
        self.tabWidget.addTab(self.mirror, _fromUtf8(""))
        edo_skeletonDrivingBallToolUI.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(edo_skeletonDrivingBallToolUI)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 344, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        edo_skeletonDrivingBallToolUI.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(edo_skeletonDrivingBallToolUI)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        edo_skeletonDrivingBallToolUI.setStatusBar(self.statusbar)
        self.actionHow_to_use = QtGui.QAction(edo_skeletonDrivingBallToolUI)
        self.actionHow_to_use.setObjectName(_fromUtf8("actionHow_to_use"))
        self.menuHelp.addAction(self.actionHow_to_use)
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(edo_skeletonDrivingBallToolUI)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(edo_skeletonDrivingBallToolUI)

    def retranslateUi(self, edo_skeletonDrivingBallToolUI):
        edo_skeletonDrivingBallToolUI.setWindowTitle(_translate("edo_skeletonDrivingBallToolUI", "edo_skeletonDrivingBallToolUI", None))
        self.connectcbs_bt.setText(_translate("edo_skeletonDrivingBallToolUI", "Connect Correct BlendShape", None))
        self.edirmodel_cb.setText(_translate("edo_skeletonDrivingBallToolUI", "8 Directions model", None))
        self.createskdb_bt.setText(_translate("edo_skeletonDrivingBallToolUI", "Create Skeleton Driving Ball", None))
        self.loadskdb_bt.setText(_translate("edo_skeletonDrivingBallToolUI", "Load SKDB", None))
        self.label_3.setText(_translate("edo_skeletonDrivingBallToolUI", "attribute:", None))
        self.label_4.setText(_translate("edo_skeletonDrivingBallToolUI", "rotation", None))
        self.loadctrl_bt.setText(_translate("edo_skeletonDrivingBallToolUI", "Load Ctrl", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.create), _translate("edo_skeletonDrivingBallToolUI", "create", None))
        self.createskdbforlcbr_bt.setText(_translate("edo_skeletonDrivingBallToolUI", "Create All SKDB To LC BodyRig", None))
        self.nofinger_cb.setText(_translate("edo_skeletonDrivingBallToolUI", "No Finger", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("edo_skeletonDrivingBallToolUI", "bodyRig(LC)", None))
        self.groupBox.setTitle(_translate("edo_skeletonDrivingBallToolUI", "mirror functions", None))
        self.mirrorskdb_bt.setText(_translate("edo_skeletonDrivingBallToolUI", "Mirror Skeleton Driving Ball", None))
        self.mirrordbs_bt.setText(_translate("edo_skeletonDrivingBallToolUI", "Mirror BS and SDK", None))
        self.from_le.setText(_translate("edo_skeletonDrivingBallToolUI", "L_", None))
        self.to_le.setText(_translate("edo_skeletonDrivingBallToolUI", "R_", None))
        self.label.setText(_translate("edo_skeletonDrivingBallToolUI", "From", None))
        self.label_2.setText(_translate("edo_skeletonDrivingBallToolUI", "to", None))
        self.switch_bt.setText(_translate("edo_skeletonDrivingBallToolUI", "--->\n"
"<---", None))
        self.mirrorsdk_bt.setText(_translate("edo_skeletonDrivingBallToolUI", "Mirror Set Driven Key", None))
        self.connectBsToBs_bt.setText(_translate("edo_skeletonDrivingBallToolUI", "Connect BS to BS", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.mirror), _translate("edo_skeletonDrivingBallToolUI", "mirror", None))
        self.menuHelp.setTitle(_translate("edo_skeletonDrivingBallToolUI", "help", None))
        self.actionHow_to_use.setText(_translate("edo_skeletonDrivingBallToolUI", "how to use", None))

